version: '3.3'

services:
    generator:
        image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-10}
        # ports:
            # - "8080:80"
        configs:
            - source: prodappsettings
              target: /publish/appsettings.json
    mail:
        image: mailhog/mailhog
        #ports:
            #- "8025:8025"
            #- "1025:1025"
    integration:
        image: my-registry:55000/gen:integration-${BUILD_NUMBER-10}
        build: .
        environment:
            - TEAMCITY_PROJECT_NAME
    
configs:
    prodappsettings:
        file: ../deploy/prodappsettings.json


